### ISSUE TITLE
Should use Image.save instead of Image.tobytes in console.

### ISSUE THREAD

**Issue by codeif** [frol/python-cropresize2#2]
> $ crop-resize ~/Downloads/img.jpg -W 20
> Traceback (most recent call last):
>   File "/Users/xyz/.virtualenvs/python2/bin/crop-resize", line 11, in <module>
>     load_entry_point('cropresize2', 'console_scripts', 'crop-resize')()
>   File "/Users/xyz/weiwei/codeif/python-cropresize2/cropresize2/**init**.py", line 134, in main
>     sys.stdout.write(new_image.tobytes(image.format))
>   File "/Users/xyz/.virtualenvs/python2/lib/python2.7/site-packages/PIL/Image.py", line 676, in tobytes
>     e = _getencoder(self.mode, encoder_name, args)
>   File "/Users/xyz/.virtualenvs/python2/lib/python2.7/site-packages/PIL/Image.py", line 440, in _getencoder
>     raise IOError("encoder %s not available" % encoder_name)
> IOError: encoder JPEG not available

Image.tobytes comments:

```
    def tobytes(self, encoder_name="raw", *args):
        """
        Return image as a bytes object.

        .. warning::

            This method returns the raw image data from the internal
            storage.  For compressed image data (e.g. PNG, JPEG) use
            :meth:`~.save`, with a BytesIO parameter for in-memory
            data.

        :param encoder_name: What encoder to use.  The default is to
                             use the standard "raw" encoder.
        :param args: Extra arguments to the encoder.
        :rtype: A bytes object.
        """
```

So we should use Image.save method output image to console.

**Comment by frol** [comment]
I believe the error message you have posted is not related to the quoted warning. The most probable cause of the traceback you have is missing JPEG library or headers. Please, reinstall Pillow and pay attention to the installation messages; it should print which encoders support was found and compiled.

**Comment by codeif** [comment]
Output to file is good, so I think it's not JPEG library problem.

**Comment by frol** [comment]
It seems that the issue was resolved, so closing this issue.
